# Generated by Django 4.1.5 on 2023-01-17 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(default=datetime.date(2023, 1, 17)),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(error_messages={'unique': 'Você já cadastrou essa receita antes'}, max_length=100, unique=True),
        ),
    ]
