# Generated by Django 4.1.5 on 2023-01-17 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_despesa_data_alter_receita_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
