# Generated by Django 4.1.5 on 2023-01-17 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_alter_despesa_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(error_messages={'unique': 'Você já cadastrou essa despesa antes'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
