# Generated by Django 4.1.5 on 2023-01-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0009_alter_despesa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
