# Generated by Django 4.1.5 on 2023-01-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0012_alter_despesa_descricao_alter_receita_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
