# Generated by Django 4.1.5 on 2023-01-21 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0013_resumomensal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumoMensal',
        ),
    ]
